appid: "331470"
publishedfileid: "null"         
visibility: "2"               
title: "Преддверие"
changenote: "Загрузка. Первая версия мода."
previewfile: "deploy/avatar.png"
project_name: "thld"
exclusions:
  - ".git"
  - ".github"
  - ".gitattributes"
  - ".gitignore"
  - ".vscode"
  - "scripts"
  - "steamcmd"
  - "build"
  - "README.md"
  - "deploy"
  - "exclusions.yml"
  - "markers.yml"
  - "game_files"
