name: Deploy to Steam Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: zImpact/es_mod_workflow/.github/workflows/deploy_to_steam.yml@main
    with:
      steam_config_path: "deploy/config.yml"
      lint_workflow_file: "lint.yml"
      branch: "main"
      check_lint_status: true
      sdk_version: "8.1.3"
      google_drive_id: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver: "1"
    secrets:
      STEAM_SHARED_SECRET: "${{ secrets.STEAM_SHARED_SECRET }}"
      STEAM_USERNAME: "${{ secrets.STEAM_USERNAME }}"
      STEAM_PASSWORD: "${{ secrets.STEAM_PASSWORD }}"