name: Lint ES mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    uses: zImpact/es_mod_workflow/.github/workflows/lint_es_mod.yml@main
    with:
      project_name: "thld"
      sdk_version: "8.1.3"
      google_drive_id: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver: "1"
      grammar_check_files: code/scenario/main.rpy
      exclusions: "exclusions.yml"
      output_type: "markdown"
      folder: "code"
      markers: "markers.yml"
      run_marker_lint: true
      run_text_lint: true
      run_basic_lint: true
      run_code_lint: true
